#!/bin/bash

echo "Starting production test server..."
echo ""
echo "Test Plan:"
echo "1. Server will start on http://localhost:3000"
echo "2. Open TWO browser tabs/windows:"
echo "   Tab 1: http://localhost:3000/chat"
echo "   Tab 2: http://localhost:3000/chat"
echo ""
echo "3. In Tab 1:"
echo "   - Click 'Create Invite Link'"
echo "   - Copy the invite link"
echo ""
echo "4. In Tab 2:"
echo "   - Paste the invite link in address bar"
echo "   - Press Enter"
echo ""
echo "5. Verify:"
echo "   - Both tabs show 'Connected' status"
echo "   - Send messages in both directions"
echo "   - Messages appear in real-time"
echo "   - Close one tab - other shows 'Disconnected'"
echo ""
echo "Press Ctrl+C to stop the server"
echo ""

npx serve out -p 3000
